### ISSUE TITLE
line data sensitive is not enough

### ISSUE THREAD

**Issue by dale502** [hkgnp/logseq-chartrender-plugin#1]
![image](https://user-images.githubusercontent.com/69394230/148328040-c7d8d75f-be60-4b00-a5e9-3c3595c22c29.png)

**Comment by hkgnp** [comment]
Hi! Thanks for sharing this! It seems like this library may not be able to handle very small numbers where the differences are in decimal points.

Will have a look around but I'm afraid that this may be a limitation that I may not be able to have a solution for 🥲.

**Comment by benjypng** [comment]
Fixed here! https://github.com/hkgnp/logseq-chartrender-plugin/releases/tag/v1.7
You can update it from the marketplace!
