### ISSUE TITLE
Plugin didn't show chart

### ISSUE THREAD

**Issue by xoyk** [hkgnp/logseq-chartrender-plugin#2]
I have tried the plugin on sample data from the example in README and chart didn't rendered

![Screenshot 2022-01-07 at 10 24 23](https://user-images.githubusercontent.com/1499826/148507428-034ca2ad-087f-469e-a98b-fec96480ec35.png)

![Screenshot 2022-01-07 at 10 22 09](https://user-images.githubusercontent.com/1499826/148507170-03cc45b3-7aed-4816-8032-822cf63dbe7c.png)

In console I got this: 
<img width="1510" alt="Screenshot 2022-01-07 at 10 19 02" src="https://user-images.githubusercontent.com/1499826/148506886-f9d45517-995b-4b43-834c-9632654aecd1.png">

Logseq app: 0.5.8 (reinstalled, refreshed, reindexed)
Chart Plugin version: 1.5

**Comment by dale502** [comment]
try give a width
bar blue 300

**Comment by benjypng** [comment]
Apologies! I have not updated the Instructions.

Yes, a width is needed. The syntax is `<type of chart> <colour> <width>`.

Examples:
```
bar green 300

pie blue 400

line gray 350

area yellow 500
```
