### ISSUE TITLE
Allow axis min and max to be set

### ISSUE THREAD

**Issue by cgrinaldi** [hkgnp/logseq-chartrender-plugin#3]
I'd like to track values that typically don't vary that much (in particular, my weight). When I use `line white 400`, and plot my weight (y) by date (x), it is only a very slight slope since it has the default range of `0` to `Max(Y)`:

![image](https://user-images.githubusercontent.com/4349348/148666375-c8fedcdb-679d-42fa-96e8-4276929b6328.png)

**Comment by benjypng** [comment]
Thanks for reporting the bug. Fixed in v1.9 (in marketplace).
