### ISSUE TITLE
Multiple series in the line chart?

### ISSUE THREAD

**Issue by tferr** [hkgnp/logseq-chartrender-plugin#4]
Super useful plugin!
Is there a way to create XY (line charts) with multiple series (i.e., more than one dataset), e.g., something like:

```
- line black 300
	- Y1
		- 2
		- 4
		- 6
	- Y2
		- 6
		- 4
		- 2
	- Common X
		- 1
		- 2
		- 3
```
where Y1 and Y2 get plotted in the same chart
Supporting completely different series [e.g., (X1, Y1), (X2, Y2)] would probably be cumbersome, but assuming  series share the same X values [e.g., (X, Y1), (X, Y2)] would already be useful, by extracting Y values from all but the last list.

**Comment by benjypng** [comment]
Hi! There is! Some of the chart formats already support multiple data formats on the same axis, e.g. the percentbar.

It's a matter of time. Will find some time to implement this!

**Comment by benjypng** [comment]
Released in v1.10.0!

**Comment by tferr** [comment]
What is the syntax? Do you have an example? I don't seem to get it working, and somehow could not get it from the gif in the README

**Comment by benjypng** [comment]
Hi it would be something like the below where in your y-axis, each series is separated by a comma.

```
line green 400
   x
        jan
        feb
        mar
   y
        200, 300
        300, 200
        400, 400
```

**Comment by emms007** [comment]
is there a way on this format to specify a color and a title of the 2 bars?
