### ISSUE TITLE
Cannot display charts

### ISSUE THREAD

**Issue by Jenae-Fung** [hkgnp/logseq-chartrender-plugin#6]
I tried to make the graph but it did not return.
![d76a9749a7f885f5520ff84169a25bb](https://user-images.githubusercontent.com/87799513/193280361-e72e4d01-4eb3-43a5-9fb7-4520fd0fd702.jpg)

**Comment by benjypng** [comment]
<img width="540" alt="Screenshot 2022-10-01 at 2 01 03 PM" src="https://user-images.githubusercontent.com/47936793/193395121-e3d05d58-c7ed-462b-90f5-f376e1983631.png">

You have to start with /chart render first, then it will be something like this:
- {{renderer :charts_fkpzdf}}
  - bar blue 300
     - x
        - A
     - y
        - 300

**Comment by Jenae-Fung** [comment]
> <img alt="Screenshot 2022-10-01 at 2 01 03 PM" width="540" src="https://user-images.githubusercontent.com/47936793/193395121-e3d05d58-c7ed-462b-90f5-f376e1983631.png">
> 
> You have to start with /chart render first, then it will be something like this:
> 
> * {{renderer :charts_fkpzdf}}
>   
>   * bar blue 300
>     
>     * x
>       
>       * A
>     * y
>       
>       * 300

It worked, thank you for your reply!
